version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:5020" # Map host port 8080 to container port 80 (nginx default)
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount config directory (read-only is often safer for config)
      - ./config:/app/config:ro
      # Mount logs directory
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
