import type { Metadata } from "next";
import { Inter, Architects_Daughter } from "next/font/google";
import "./globals.css";
import { RootProviders } from "@/lib/providers/root-provider";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const architects_daughter = Architects_Daughter({
  subsets: ['latin'],
  variable: '--font-architects-daughter',
  weight: '400',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${inter.variable} ${architects_daughter.variable} font-inter antialiased tracking-tight`}>
        <div className="flex flex-col min-h-screen overflow-hidden">
          <RootProviders>
            {children}
          </RootProviders>
        </div>
      </body>
    </html>
  );
}
