import type { Metadata } from "next";
import { Inter, Architects_Daughter } from "next/font/google";
import "@/app/globals.css";
import { getCurrentUser } from "@/lib/session";
import { AccountInfo } from "@/types";
import { RootProviders } from "@/lib/providers/root-provider";
import { Toaster } from "@/components/ui/toaster";
import { TailwindIndicator } from "@/components/layout/TailwindIndicator";
import { AuthenticationLayout } from "@/components/layout/auth-panel";


const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
})

const architects_daughter = Architects_Daughter({
    subsets: ['latin'],
    variable: '--font-architects-daughter',
    weight: '400',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const user = (await getCurrentUser()) as AccountInfo;
    return (
        <html lang="en">
            <body className={`${inter.variable} ${architects_daughter.variable} font-inter antialiased tracking-tight`}>
                <div className="flex flex-col min-h-screen overflow-hidden">
                    <RootProviders>
                        <AuthenticationLayout>
                            {children}
                        </AuthenticationLayout>
                        <Toaster />
                        <TailwindIndicator />
                    </RootProviders>
                </div>
            </body>
        </html>
    );
}
