"""init_tables

Revision ID: 02c3db227d01
Revises: 
Create Date: 2025-04-29 09:13:31.547811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c3db227d01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名，唯一'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='电子邮箱，唯一'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号码'),
    sa.Column('gender', sa.SMALLINT(), nullable=True, comment='性别，0-未知，1-男，2-女'),
    sa.Column('password_hashed', sa.String(length=255), nullable=False, comment='密码哈希值'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='账户是否激活 (True: 激活, False: 禁用)'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    comment='系统账户信息表'
    )
    op.create_table('json_schemas',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Schema 名称'),
    sa.Column('schema', sa.JSON(), nullable=False, comment='JSON Schema 定义'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注信息'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('json_values',
    sa.Column('value', sa.JSON(), nullable=False, comment='JSON值'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注信息'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_tokens',
    sa.Column('account_id', sa.Integer(), nullable=False, comment='关联的账户ID (accounts.id)，唯一'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='API 访问令牌字符串，唯一'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('account_id', name='uq_account_tokens_account_id'),
    sa.UniqueConstraint('token'),
    comment='账户 API 访问令牌表'
    )
    op.create_table('company',
    sa.Column('name', sa.String(length=255), nullable=False, comment='公司名称'),
    sa.Column('extra_value', sa.JSON(), nullable=True, comment='附加JSON格式数据'),
    sa.Column('extra_schema_id', sa.Integer(), nullable=True, comment='关联的JSON Schema ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='公司描述'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['extra_schema_id'], ['json_schemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('name', sa.String(length=255), nullable=False, comment='员工姓名'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='所属公司ID'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='电子邮箱地址'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('birthdate', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='居住地址'),
    sa.Column('gender', sa.SMALLINT(), nullable=True, comment='性别，0-未知，1-男，2-女'),
    sa.Column('extra_value', sa.JSON(), nullable=True, comment='附加JSON格式数据'),
    sa.Column('extra_schema_id', sa.Integer(), nullable=True, comment='关联的JSON Schema ID'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['extra_schema_id'], ['json_schemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_company',
    sa.Column('account_id', sa.Integer(), nullable=False, comment='账户ID，关联 accounts.id'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='公司ID，关联 company.id'),
    sa.Column('role', sa.String(length=32), nullable=False, comment='账户在该公司中的角色 (owner, admin, user)'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'company_id', name='uix_account_company'),
    comment='账户与公司的关联表，定义账户在公司中的角色'
    )
    op.create_table('department',
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父部门ID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='所属公司ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='部门名称'),
    sa.Column('leader_id', sa.Integer(), nullable=True, comment='部门负责人ID'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注信息'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('name', sa.String(length=64), nullable=False, comment='职位名称'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='所属公司ID'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注信息'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('company_id', sa.Integer(), nullable=False, comment='公司ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='候选人姓名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='电子邮箱'),
    sa.Column('position_id', sa.Integer(), nullable=False, comment='应聘职位ID'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='目标部门ID'),
    sa.Column('interview_date', sa.DateTime(), nullable=False, comment='面试日期'),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'INTERVIEWED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='candidatestatus'), nullable=False, comment='候选人状态'),
    sa.Column('interviewer_id', sa.Integer(), nullable=True, comment='面试官ID'),
    sa.Column('evaluation', sa.Text(), nullable=True, comment='面试评价'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注信息'),
    sa.Column('extra_value', sa.JSON(), nullable=True, comment='附加JSON格式数据'),
    sa.Column('extra_schema_id', sa.Integer(), nullable=True, comment='关联的JSON Schema ID'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['extra_schema_id'], ['json_schemas.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_position',
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='员工ID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='公司ID'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='部门ID'),
    sa.Column('position_id', sa.Integer(), nullable=False, comment='职位ID'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='入职时间'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='离职时间'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注信息'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_position')
    op.drop_table('candidate')
    op.drop_table('position')
    op.drop_table('department')
    op.drop_table('account_company')
    op.drop_table('employee')
    op.drop_table('company')
    op.drop_table('account_tokens')
    op.drop_table('json_values')
    op.drop_table('json_schemas')
    op.drop_table('accounts')
    # ### end Alembic commands ###
