"""add_entity_type_to_json_schemas

Revision ID: af6203bb8220
Revises: 02c3db227d01
Create Date: 2025-05-06 13:44:35.936823

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af6203bb8220"
down_revision = "02c3db227d01"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account_tokens", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_account_tokens_account_id", ["account_id"]
        )

    with op.batch_alter_table("json_schemas", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "entity_type",
                sa.Enum(
                    "EMPLOYEE",
                    "CANDIDATE",
                    "COMPANY",
                    "DEPARTMENT",
                    "POSITION",
                    "GENERAL",
                    name="schemaentitytype",
                ),
                nullable=False,
                comment="Schema适用的实体类型",
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_system",
                sa.Boolean(),
                nullable=False,
                comment="是否为系统预设Schema",
            )
        )
        batch_op.add_column(
            sa.Column("version", sa.Integer(), nullable=False, comment="Schema版本号")
        )
        batch_op.add_column(
            sa.Column(
                "parent_schema_id",
                sa.Integer(),
                nullable=True,
                comment="父Schema ID，用于版本管理",
            )
        )
        batch_op.add_column(
            sa.Column("company_id", sa.Integer(), nullable=True, comment="所属公司ID")
        )
        batch_op.add_column(
            sa.Column("ui_schema", sa.JSON(), nullable=True, comment="UI展示相关的配置")
        )
        batch_op.create_foreign_key(
            "fk_schema_parent", "json_schemas", ["parent_schema_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_schema_company", "company", ["company_id"], ["id"]
        )

    with op.batch_alter_table("json_values", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "schema_id",
                sa.Integer(),
                nullable=False,
                comment="关联的JSON Schema ID",
            )
        )
        batch_op.add_column(
            sa.Column(
                "entity_id",
                sa.Integer(),
                nullable=False,
                comment="关联的实体ID，如员工ID、候选人ID等",
            )
        )
        batch_op.add_column(
            sa.Column(
                "entity_type",
                sa.String(length=50),
                nullable=False,
                comment="关联的实体类型，如'employee'、'candidate'等",
            )
        )
        batch_op.create_index(
            "ix_json_value_entity", ["entity_type", "entity_id"], unique=False
        )
        batch_op.create_index("ix_json_value_schema", ["schema_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_value_schema", "json_schemas", ["schema_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("json_values", schema=None) as batch_op:
        batch_op.drop_constraint("fk_value_schema", type_="foreignkey")
        batch_op.drop_index("ix_json_value_schema")
        batch_op.drop_index("ix_json_value_entity")
        batch_op.drop_column("entity_type")
        batch_op.drop_column("entity_id")
        batch_op.drop_column("schema_id")

    with op.batch_alter_table("json_schemas", schema=None) as batch_op:
        batch_op.drop_constraint("fk_schema_parent", type_="foreignkey")
        batch_op.drop_constraint("fk_schema_company", type_="foreignkey")
        batch_op.drop_column("ui_schema")
        batch_op.drop_column("company_id")
        batch_op.drop_column("parent_schema_id")
        batch_op.drop_column("version")
        batch_op.drop_column("is_system")
        batch_op.drop_column("entity_type")

    with op.batch_alter_table("account_tokens", schema=None) as batch_op:
        batch_op.drop_constraint("uq_account_tokens_account_id", type_="unique")

    # ### end Alembic commands ###
